### ISSUE TITLE
Plan the Mouse class

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#11]
![image](https://cloud.githubusercontent.com/assets/4276762/23564121/3b131268-fffe-11e6-8698-d18510477eae.png)

**Comment by blhough** [comment]
Does this seem sensible?
Thoughts? Suggestions?

**Comment by klanmiko** [comment]
The mouse class should also have a few control macros, for example: fast and slow 90, 45 degree turns. A way to traverse a diagonal corridor vs a purely straight one with no obstacles.

The hardware class should record the current direction of the mouse, the wheel speeds and distances for each wheel, the perceived location of the mouse in cell coordinates. It should also record all the current values of the sensors.
