### ISSUE TITLE
Draw Path in Simulation

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#14]

**Comment by ids1024** [comment]
I think the way to do this that would be the least of a hack is if the path is a vector (or otherwise allowed iterating) and is set as a member of the `Maze` class, so the simulator could access it while rendering.

**Comment by blhough** [comment]
That sounds very sensible

**Comment by blhough** [comment]
findPath seems to be working from looking at the debugger.

**Comment by ids1024** [comment]
This is now implemented.
