### ISSUE TITLE
Create classes for hardware components

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#18]
The [hardware](https://docs.google.com/spreadsheets/d/1v4yZ6iHlCe61Mf9AZj_Za-24lgkbLBGUx5Sx-UTaCA4/edit#gid=0) for the mouse has been ordered so we need to start planning that portion of the code.

For now let's just create an empty class for each component that we will be interfacing with.

Create empty class:
- [x] Motor
- [x] Encoder
- [x] RangeFinder
- [x] Led

Additionally we will want a class to encapsulate all the components.
I am not sure a good name for this class (Hardware??)
Create empty class:
- [x] \<Good class name here\>

**Comment by daniel9a** [comment]
@blhough  In what file should the empty classes go?

**Comment by blhough** [comment]
Each will have their own header and cpp file

**Comment by blhough** [comment]
View comment on dcf2b617b9a1cb13876d5bec564ea51ec4820848

**Comment by blhough** [comment]
Only the class definition goes in the header. The function implementations go in the cpp

**Comment by blhough** [comment]
The class definition for Motor is still in the cpp
