### ISSUE TITLE
Refactor Path to use a Vector

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#20]
Refactor Path to use a Vector and store generate paths in Maze.

may want to change Maze::findPath to be void and add a getter for the path that returns a pointer/ref.
or something to the same effect. 

Also may want to expose the vector iterators or define our own

**Comment by ids1024** [comment]
Are we going to want to add any members to `Path` other than just iterating/pushing/etc? If not, it might be better to remove the `Path` class and just use `vector<DirectionVector>`.

**Comment by blhough** [comment]
I can't think of any special members it might need.

If we wrap in a class we can prevent nonsensical things like erasing from the middle of the path.
But misuses like that are unlikely to happen by accident.
Use your best discretion.
