### ISSUE TITLE
add a function for getting the angle between directions

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#21]
ex. angleDiff( N, W) = 90
angleDiff( W, N) = -90

May want an absolute version too

angleDiffAbs( W, N) = 90

may want it to return an enum since the values are discrete
may want to overload operator

**Comment by ids1024** [comment]
@cnagda Did you try to push this to `dev`? If so it didn't work; the repository is now configured so you can't push directly to `dev`, but changes have to go through a pull request.

**Comment by klanmiko** [comment]
For the person implementing this:

Measure the angle clockwise from argument 1 to argument 2

**Comment by blhough** [comment]
@cnagda  checkout the [readme](https://github.com/RoboticsClubAtUCDavis/micromouse/blob/dev/README.md) for up to date instructions on contributing
