### ISSUE TITLE
All Nodes that are "posts" should be set to not exist

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#22]
![image](https://cloud.githubusercontent.com/assets/4276762/23529925/5f35e81e-ff54-11e6-9752-5d4c27cd9248.png)

The mouse can never travel to these nodes so they need to be set to not exist.
No special case needs to be made for the center finish even though there is no post there.

This should occur in Maze::reset()

**Comment by klanmiko** [comment]
I think this is best implemented in the setWall function

**Comment by ids1024** [comment]
@klanmiko The suggestion is that they should never exist. The only case where crossing one of these "posts" would be possible is in a square of 4 cells, but that occurs only at the goal, and is thus irrelevant.

**Comment by klanmiko** [comment]
Oh okay, makes sense.
