### ISSUE TITLE
Unit Tests for Coordinates

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#26]

**Comment by klanmiko** [comment]
@blhough do you have suggestions for unit testing libraries? I'm used to node.js and mocha.

**Comment by blhough** [comment]
There is already a unit test library in the project. #15 
We are trying to match [this style](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#bdd-style)

Checkout [Test/Test-Direction.cpp](https://github.com/RoboticsClubAtUCDavis/micromouse/blob/dev/Test/Test-Direction.cpp) for another example.

**Comment by blhough** [comment]
We may want to consider adding a mocking framework too later on for the sensors and such.
https://github.com/eranpeer/FakeIt
