### ISSUE TITLE
How to run SConstruct

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#54]
I get this when I try to run it. 
```
  File "SConstruct", line 14, in <module>
    sfml_libs = Split('sfml-graphics sfml-window sfml-system')
NameError: name 'Split' is not defined
```

**Comment by ids1024** [comment]
Are you trying to execute it directly (`./SConstruct` or `python SConstruct`)?

The correct way to run scons is with the `scons` command.

**Comment by blhough** [comment]
Okay now I get this
```
scons: Reading SConscript files ...

scons: *** An executable should have exactly one target with the suffix: .exe
File "D:\Repos\micromouse\SConstruct", line 22, in <module>
```


changing line 17 to
`OBJPREFIX='build/linux/', PROGPREFIX='build/linux/', PROGSUFFIX='.exe')`
does not fix it

**Comment by ids1024** [comment]
Hm, I though it added the suffix on Windows. Adding a `.exe` manually to the end of the target name might fix it...

**Comment by blhough** [comment]
It did not fix it either. Maybe at the next meeting you can look at it.
