### ISSUE TITLE
Define and Implement LedRGB

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#55]
This class represents an RGB (red-green-blue) LED. An RGB LED is a light emitting diode that has three channels, one for each color. By varying the brightness of each of the three channels, an RGB LED can create any color.

Essentially an RBG LED is just 3 individual LEDs combined together. This is convenient because we already have an `Led` class.

The `LedRGB` class should have the following public members:
- [x] Default constructor: `LedRGB();`
- [x] Custom constructor: `LedRGB( unsigned redPin, unsigned greenPin, unsigned bluePin);`
- [x] `void setRGB(unsigned r, unsigned g, unsigned b);`
  - Takes three values between 0-255 and sets the color accordingly.
- [x] `void setBrightness( unsigned percent );`
  - `percent` is in the range [0,100]
- [x] `void turnOn();`
- [x] `void turnOff();`

Since the `Led` class has not been merged in yet, be sure to branch of your led branch.

Do not worry about inheritance yet but that will added later.

**Comment by daniel9a** [comment]
i have a question so do i push the LedRGB to the led branch? or do i create a LedRGB branch and merge it to the led branch?

**Comment by blhough** [comment]
(for the sake of practicing git)  we do not want to merge ledRGB into led because led is its own feature. 
With the `led` branch checked out do
`git pull origin dev` to update from dev. Then do
`git checkout -b ledrgb` to make the new branch then add your commits and push to github
