### ISSUE TITLE
Create and Implement PIDController

### ISSUE THREAD

**Issue by blhough** [RoboticsClubAtUCDavis/micromouse#66]
A very good intro to pid controllers: https://www.youtube.com/watch?v=4Y7zG48uHRo

wikipedia explanation: https://en.wikipedia.org/wiki/PID_controller#Fundamental_operation

We will want to be able to:
- set the constants P, I, and D.
- get the correction factor based on the current error and the delta "time"

*(I say "time" because we may choose to use delta counts or distance in some instances instead but it is effectively the same)*

**Comment by klanmiko** [comment]
How do you plan to tune it?

Also will you measure error between both encoders as well, or measure the error for each wheel to the expected ending point

**Comment by blhough** [comment]
manually I guess.

I am not sure what you mean by error between encoders?

For moveForward I plan to use a controller for the speed, one for the distance, and two for keeping the mouse centered and straight. For speed and distance I use an average of the encoders so that it does not try to counteract the controllers keeping the mouse centered and straight. Eg. it's okay if one encoder say we went 99mm and the other says 101mm as long as the mouse is actually straight according to the other controllers.

**Comment by klanmiko** [comment]
So we're using 2 encoders, I'm just asking how you plan to keep the robot straight and also make sure it reaches a distance accurately. By error I mean the difference in left in right encoders to keep it straight, and the difference between the average encoder value and the distance the robot should travel. 

I would suggest using 2 separate PID controllers, one for straight travel and one for distance
