### ISSUE TITLE
Maze generator

### ISSUE THREAD

**Issue by ids1024** [RoboticsClubAtUCDavis/micromouse#8]
The [Recursive Backtracking](https://en.wikipedia.org/wiki/Maze_generation_algorithm#Recursive_backtracker) algorithm seems to give the best results while being fairly simple.

If you find another algorithm that looks better go for it

The function should be a static member of the Maze class. Look at `Maze::fromFile` for reference. 
At a minimum the function should take in an int seed to allow for the same maze to be generated again. Otherwise a random maze should be generated.

**Comment by blhough** [comment]
@klanmiko can you do this?
If there is some other area you would like to work on let me know or self assign whatever.

**Comment by blhough** [comment]
I'm sorry I forgot to mention this before. The 4 four finish cells will always have exactly one entrance (one of the eight walls will be missing). I hope it is not too difficult to add.
